In [1]:
import numpy as np
import funciones.template_funciones_dos as tf2

In [2]:
A_ejemplo = np.array([
   [0, 1, 1, 1, 0, 0, 0, 0],
   [1, 0, 1, 1, 0, 0, 0, 0],
   [1, 1, 0, 1, 0, 1, 0, 0],
   [1, 1, 1, 0, 1, 0, 0, 0],
   [0, 0, 0, 1, 0, 1, 1, 1],
   [0, 0, 1, 0, 1, 0, 1, 1],
   [0, 0, 0, 0, 1, 1, 0, 1],
   [0, 0, 0, 0, 1, 1, 1, 0]
])

In [3]:
L = tf2.calcula_L(A_ejemplo)
L

array([[ 3, -1, -1, -1,  0,  0,  0,  0],
       [-1,  3, -1, -1,  0,  0,  0,  0],
       [-1, -1,  4, -1,  0, -1,  0,  0],
       [-1, -1, -1,  4, -1,  0,  0,  0],
       [ 0,  0,  0, -1,  4, -1, -1, -1],
       [ 0,  0, -1,  0, -1,  4, -1, -1],
       [ 0,  0,  0,  0, -1, -1,  3, -1],
       [ 0,  0,  0,  0, -1, -1, -1,  3]])

In [4]:
R = tf2.calcula_R(A_ejemplo)
R

array([[-0.32142857,  0.67857143,  0.57142857,  0.57142857, -0.42857143,
        -0.42857143, -0.32142857, -0.32142857],
       [ 0.67857143, -0.32142857,  0.57142857,  0.57142857, -0.42857143,
        -0.42857143, -0.32142857, -0.32142857],
       [ 0.57142857,  0.57142857, -0.57142857,  0.42857143, -0.57142857,
         0.42857143, -0.42857143, -0.42857143],
       [ 0.57142857,  0.57142857,  0.42857143, -0.57142857,  0.42857143,
        -0.57142857, -0.42857143, -0.42857143],
       [-0.42857143, -0.42857143, -0.57142857,  0.42857143, -0.57142857,
         0.42857143,  0.57142857,  0.57142857],
       [-0.42857143, -0.42857143,  0.42857143, -0.57142857,  0.42857143,
        -0.57142857,  0.57142857,  0.57142857],
       [-0.32142857, -0.32142857, -0.42857143, -0.42857143,  0.57142857,
         0.57142857, -0.32142857,  0.67857143],
       [-0.32142857, -0.32142857, -0.42857143, -0.42857143,  0.57142857,
         0.57142857,  0.67857143, -0.32142857]])

In [5]:
v_1 = np.ones(8)

np.allclose(R @ v_1, np.zeros(8))

True

In [6]:
L @ v_1

array([0., 0., 0., 0., 0., 0., 0., 0.])

In [7]:
P = np.array([[1,-1,-1], [1,1,-1],[1,0,2]])
P_inv = np.linalg.inv(P)
D = np.array([[0,0,0],[0,1,0],[0,0,2]])

P @ D @ P_inv

array([[ 0.83333333, -0.16666667, -0.66666667],
       [-0.16666667,  0.83333333, -0.66666667],
       [-0.66666667, -0.66666667,  1.33333333]])

In [8]:
autovector, autovalor = tf2.metpotI2(L, 0.1)
autovalor

l:  1.1574984766810825


0.7639320225002102

In [9]:
data = tf2.laplaciano_iterativo(A_ejemplo, 2)

data

IndexError: index 6 is out of bounds for axis 0 with size 4